import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageDir = path.join(root, "node_modules/ratex-wasm");
let css = await readFile(path.join(packageDir, "fonts.css"), "utf8");
const declarations = [];
for (const match of css.matchAll(/@font-face\s*\{([^}]+)\}/g)) {
  const rule = match[1];
  const property = (name) => new RegExp(`${name}:\\s*([^;]+);`).exec(rule)?.[1];
  declarations.push(`${property("font-style")} ${property("font-weight")} 16px ${property("font-family")}`);
}
for (const match of [...css.matchAll(/src:\s*url\(([^)]+\.woff2)\)[^;]+;/g)]) {
  const bytes = await readFile(path.join(packageDir, match[1]));
  css = css.replace(match[0], `src: url(data:font/woff2;base64,${bytes.toString("base64")}) format("woff2");`);
}
const outDir = path.join(root, "client/vendor");
await mkdir(outDir, { recursive: true });
await writeFile(path.join(outDir, "fonts.ts"),
  `// Generated by scripts/embed-fonts.mjs from ratex-wasm/fonts.css and its WOFF2 files.\n` +
  `export const FONT_CSS = ${JSON.stringify(css)};\n` +
  `export const FONT_DECLARATIONS = ${JSON.stringify(declarations)};\n`);
console.log(`Embedded ${declarations.length} font faces (${css.length} CSS characters)`);
